#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 137
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 57
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 10
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 7

enum {
  anon_sym_STARsave_COLON = 1,
  anon_sym_STARif_COLON = 2,
  anon_sym_STARwhile_COLON = 3,
  anon_sym_STARfor_COLON = 4,
  anon_sym_STARquestion_COLON = 5,
  anon_sym_GT_GT = 6,
  anon_sym_EQ = 7,
  anon_sym_DQUOTE = 8,
  anon_sym_LBRACK = 9,
  anon_sym_RBRACK = 10,
  sym_comma_divider = 11,
  anon_sym_LBRACE = 12,
  anon_sym_RBRACE = 13,
  anon_sym_DASH_GT = 14,
  sym_lessThan_operator = 15,
  sym_moreThan_operator = 16,
  sym_in_operator = 17,
  aux_sym_identifier_token1 = 18,
  sym_question = 19,
  sym_number = 20,
  anon_sym_RPAREN = 21,
  sym__newline = 22,
  sym__indent = 23,
  sym__dedent = 24,
  sym__string_start = 25,
  sym__string_content = 26,
  sym__string_end = 27,
  sym__comment = 28,
  sym_source_file = 29,
  sym__definition = 30,
  sym__block_start = 31,
  sym__block_end = 32,
  sym_block = 33,
  sym__command_definition = 34,
  sym_save_command_definition = 35,
  sym__function_definition = 36,
  sym_if_function_definition = 37,
  sym_while_function_definition = 38,
  sym_for_function_definition = 39,
  sym_question_function_definition = 40,
  sym_variable_definition = 41,
  sym__keyword_definition = 42,
  sym__type = 43,
  sym_string_type = 44,
  sym_array_type = 45,
  sym_dictionary_type = 46,
  sym_dictionary_pair = 47,
  sym__expression = 48,
  sym__operator = 49,
  sym_equal_operator = 50,
  sym_identifier = 51,
  sym_plain_text = 52,
  aux_sym_source_file_repeat1 = 53,
  aux_sym_variable_definition_repeat1 = 54,
  aux_sym_array_type_repeat1 = 55,
  aux_sym_dictionary_type_repeat1 = 56,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_STARsave_COLON] = "*save:",
  [anon_sym_STARif_COLON] = "*if:",
  [anon_sym_STARwhile_COLON] = "*while:",
  [anon_sym_STARfor_COLON] = "*for:",
  [anon_sym_STARquestion_COLON] = "*question:",
  [anon_sym_GT_GT] = ">>",
  [anon_sym_EQ] = "=",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_comma_divider] = "comma_divider",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_DASH_GT] = "->",
  [sym_lessThan_operator] = "lessThan_operator",
  [sym_moreThan_operator] = "moreThan_operator",
  [sym_in_operator] = "in_operator",
  [aux_sym_identifier_token1] = "identifier_token1",
  [sym_question] = "question",
  [sym_number] = "number",
  [anon_sym_RPAREN] = ")",
  [sym__newline] = "_newline",
  [sym__indent] = "_indent",
  [sym__dedent] = "_dedent",
  [sym__string_start] = "_string_start",
  [sym__string_content] = "_string_content",
  [sym__string_end] = "_string_end",
  [sym__comment] = "_comment",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym__block_start] = "_block_start",
  [sym__block_end] = "_block_end",
  [sym_block] = "block",
  [sym__command_definition] = "_command_definition",
  [sym_save_command_definition] = "save_command_definition",
  [sym__function_definition] = "_function_definition",
  [sym_if_function_definition] = "if_function_definition",
  [sym_while_function_definition] = "while_function_definition",
  [sym_for_function_definition] = "for_function_definition",
  [sym_question_function_definition] = "question_function_definition",
  [sym_variable_definition] = "variable_definition",
  [sym__keyword_definition] = "_keyword_definition",
  [sym__type] = "_type",
  [sym_string_type] = "string_type",
  [sym_array_type] = "array_type",
  [sym_dictionary_type] = "dictionary_type",
  [sym_dictionary_pair] = "dictionary_pair",
  [sym__expression] = "_expression",
  [sym__operator] = "_operator",
  [sym_equal_operator] = "equal_operator",
  [sym_identifier] = "identifier",
  [sym_plain_text] = "plain_text",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_variable_definition_repeat1] = "variable_definition_repeat1",
  [aux_sym_array_type_repeat1] = "array_type_repeat1",
  [aux_sym_dictionary_type_repeat1] = "dictionary_type_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_STARsave_COLON] = anon_sym_STARsave_COLON,
  [anon_sym_STARif_COLON] = anon_sym_STARif_COLON,
  [anon_sym_STARwhile_COLON] = anon_sym_STARwhile_COLON,
  [anon_sym_STARfor_COLON] = anon_sym_STARfor_COLON,
  [anon_sym_STARquestion_COLON] = anon_sym_STARquestion_COLON,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_comma_divider] = sym_comma_divider,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [sym_lessThan_operator] = sym_lessThan_operator,
  [sym_moreThan_operator] = sym_moreThan_operator,
  [sym_in_operator] = sym_in_operator,
  [aux_sym_identifier_token1] = aux_sym_identifier_token1,
  [sym_question] = sym_question,
  [sym_number] = sym_number,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym__newline] = sym__newline,
  [sym__indent] = sym__indent,
  [sym__dedent] = sym__dedent,
  [sym__string_start] = sym__string_start,
  [sym__string_content] = sym__string_content,
  [sym__string_end] = sym__string_end,
  [sym__comment] = sym__comment,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym__block_start] = sym__block_start,
  [sym__block_end] = sym__block_end,
  [sym_block] = sym_block,
  [sym__command_definition] = sym__command_definition,
  [sym_save_command_definition] = sym_save_command_definition,
  [sym__function_definition] = sym__function_definition,
  [sym_if_function_definition] = sym_if_function_definition,
  [sym_while_function_definition] = sym_while_function_definition,
  [sym_for_function_definition] = sym_for_function_definition,
  [sym_question_function_definition] = sym_question_function_definition,
  [sym_variable_definition] = sym_variable_definition,
  [sym__keyword_definition] = sym__keyword_definition,
  [sym__type] = sym__type,
  [sym_string_type] = sym_string_type,
  [sym_array_type] = sym_array_type,
  [sym_dictionary_type] = sym_dictionary_type,
  [sym_dictionary_pair] = sym_dictionary_pair,
  [sym__expression] = sym__expression,
  [sym__operator] = sym__operator,
  [sym_equal_operator] = sym_equal_operator,
  [sym_identifier] = sym_identifier,
  [sym_plain_text] = sym_plain_text,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_variable_definition_repeat1] = aux_sym_variable_definition_repeat1,
  [aux_sym_array_type_repeat1] = aux_sym_array_type_repeat1,
  [aux_sym_dictionary_type_repeat1] = aux_sym_dictionary_type_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_STARsave_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STARif_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STARwhile_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STARfor_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STARquestion_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_comma_divider] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_lessThan_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_moreThan_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_in_operator] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_identifier_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_question] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym__dedent] = {
    .visible = false,
    .named = true,
  },
  [sym__string_start] = {
    .visible = false,
    .named = true,
  },
  [sym__string_content] = {
    .visible = false,
    .named = true,
  },
  [sym__string_end] = {
    .visible = false,
    .named = true,
  },
  [sym__comment] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym__block_start] = {
    .visible = false,
    .named = true,
  },
  [sym__block_end] = {
    .visible = false,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym__command_definition] = {
    .visible = false,
    .named = true,
  },
  [sym_save_command_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__function_definition] = {
    .visible = false,
    .named = true,
  },
  [sym_if_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_while_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_for_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_question_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__keyword_definition] = {
    .visible = false,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [sym_string_type] = {
    .visible = true,
    .named = true,
  },
  [sym_array_type] = {
    .visible = true,
    .named = true,
  },
  [sym_dictionary_type] = {
    .visible = true,
    .named = true,
  },
  [sym_dictionary_pair] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__operator] = {
    .visible = false,
    .named = true,
  },
  [sym_equal_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_plain_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_variable_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dictionary_type_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_condition = 1,
  field_for_block = 2,
  field_if_block = 3,
  field_while_block = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_condition] = "condition",
  [field_for_block] = "for_block",
  [field_if_block] = "if_block",
  [field_while_block] = "while_block",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 2},
  [4] = {.index = 6, .length = 4},
  [5] = {.index = 10, .length = 4},
  [6] = {.index = 14, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_condition, 1},
    {field_if_block, 2},
  [2] =
    {field_condition, 1},
    {field_while_block, 2},
  [4] =
    {field_condition, 1},
    {field_for_block, 2},
  [6] =
    {field_condition, 1},
    {field_condition, 2},
    {field_condition, 3},
    {field_if_block, 4},
  [10] =
    {field_condition, 1},
    {field_condition, 2},
    {field_condition, 3},
    {field_while_block, 4},
  [14] =
    {field_condition, 1},
    {field_condition, 2},
    {field_condition, 3},
    {field_for_block, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 2,
  [6] = 6,
  [7] = 7,
  [8] = 7,
  [9] = 9,
  [10] = 10,
  [11] = 9,
  [12] = 10,
  [13] = 10,
  [14] = 9,
  [15] = 9,
  [16] = 16,
  [17] = 10,
  [18] = 18,
  [19] = 18,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 20,
  [25] = 21,
  [26] = 26,
  [27] = 27,
  [28] = 23,
  [29] = 29,
  [30] = 18,
  [31] = 22,
  [32] = 32,
  [33] = 22,
  [34] = 34,
  [35] = 22,
  [36] = 36,
  [37] = 18,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 32,
  [43] = 26,
  [44] = 44,
  [45] = 34,
  [46] = 46,
  [47] = 47,
  [48] = 29,
  [49] = 27,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 40,
  [57] = 57,
  [58] = 54,
  [59] = 52,
  [60] = 50,
  [61] = 57,
  [62] = 38,
  [63] = 63,
  [64] = 53,
  [65] = 65,
  [66] = 63,
  [67] = 65,
  [68] = 55,
  [69] = 51,
  [70] = 70,
  [71] = 41,
  [72] = 44,
  [73] = 47,
  [74] = 70,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 78,
  [82] = 82,
  [83] = 79,
  [84] = 76,
  [85] = 78,
  [86] = 79,
  [87] = 78,
  [88] = 82,
  [89] = 75,
  [90] = 79,
  [91] = 77,
  [92] = 92,
  [93] = 34,
  [94] = 27,
  [95] = 29,
  [96] = 34,
  [97] = 26,
  [98] = 32,
  [99] = 38,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 50,
  [104] = 104,
  [105] = 38,
  [106] = 104,
  [107] = 32,
  [108] = 26,
  [109] = 109,
  [110] = 29,
  [111] = 111,
  [112] = 102,
  [113] = 113,
  [114] = 27,
  [115] = 100,
  [116] = 50,
  [117] = 111,
  [118] = 109,
  [119] = 119,
  [120] = 119,
  [121] = 121,
  [122] = 122,
  [123] = 101,
  [124] = 113,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 128,
  [132] = 129,
  [133] = 130,
  [134] = 134,
  [135] = 135,
  [136] = 136,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(30);
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == ')') ADVANCE(53);
      if (lookahead == '*') ADVANCE(14);
      if (lookahead == ',') ADVANCE(41);
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == '<') ADVANCE(45);
      if (lookahead == '=') ADVANCE(37);
      if (lookahead == '>') ADVANCE(47);
      if (lookahead == '[') ADVANCE(39);
      if (lookahead == ']') ADVANCE(40);
      if (lookahead == 'i') ADVANCE(20);
      if (lookahead == '{') ADVANCE(42);
      if (lookahead == '}') ADVANCE(43);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(38);
      if (lookahead == '=') ADVANCE(37);
      if (lookahead == '?') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 2:
      if (lookahead == ':') ADVANCE(32);
      END_STATE();
    case 3:
      if (lookahead == ':') ADVANCE(34);
      END_STATE();
    case 4:
      if (lookahead == ':') ADVANCE(31);
      END_STATE();
    case 5:
      if (lookahead == ':') ADVANCE(33);
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(35);
      END_STATE();
    case 7:
      if (lookahead == '<') ADVANCE(45);
      if (lookahead == '=') ADVANCE(37);
      if (lookahead == '>') ADVANCE(46);
      if (lookahead == 'i') ADVANCE(20);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(7)
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(44);
      END_STATE();
    case 9:
      if (lookahead == '>') ADVANCE(36);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(28);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(4);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(5);
      END_STATE();
    case 14:
      if (lookahead == 'f') ADVANCE(22);
      if (lookahead == 'i') ADVANCE(15);
      if (lookahead == 'q') ADVANCE(27);
      if (lookahead == 's') ADVANCE(10);
      if (lookahead == 'w') ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == 'f') ADVANCE(2);
      END_STATE();
    case 16:
      if (lookahead == 'h') ADVANCE(17);
      END_STATE();
    case 17:
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 18:
      if (lookahead == 'i') ADVANCE(23);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(13);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(48);
      END_STATE();
    case 21:
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(24);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 24:
      if (lookahead == 'r') ADVANCE(3);
      END_STATE();
    case 25:
      if (lookahead == 's') ADVANCE(26);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(18);
      END_STATE();
    case 27:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 28:
      if (lookahead == 'v') ADVANCE(12);
      END_STATE();
    case 29:
      if (eof) ADVANCE(30);
      if (lookahead == '*') ADVANCE(14);
      if (lookahead == '-') ADVANCE(8);
      if (lookahead == '>') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(29)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_STARsave_COLON);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_STARif_COLON);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_STARwhile_COLON);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_STARfor_COLON);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_STARquestion_COLON);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_comma_divider);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_lessThan_operator);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_moreThan_operator);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_moreThan_operator);
      if (lookahead == '>') ADVANCE(36);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_in_operator);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (lookahead == '?') ADVANCE(51);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_identifier_token1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_question);
      if (lookahead == '?' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 29},
  [2] = {.lex_state = 29, .external_lex_state = 2},
  [3] = {.lex_state = 29, .external_lex_state = 2},
  [4] = {.lex_state = 29, .external_lex_state = 2},
  [5] = {.lex_state = 29, .external_lex_state = 2},
  [6] = {.lex_state = 29},
  [7] = {.lex_state = 29, .external_lex_state = 2},
  [8] = {.lex_state = 29},
  [9] = {.lex_state = 0, .external_lex_state = 3},
  [10] = {.lex_state = 0, .external_lex_state = 3},
  [11] = {.lex_state = 0, .external_lex_state = 3},
  [12] = {.lex_state = 0, .external_lex_state = 3},
  [13] = {.lex_state = 0, .external_lex_state = 3},
  [14] = {.lex_state = 0, .external_lex_state = 3},
  [15] = {.lex_state = 0, .external_lex_state = 3},
  [16] = {.lex_state = 0, .external_lex_state = 3},
  [17] = {.lex_state = 0, .external_lex_state = 3},
  [18] = {.lex_state = 0, .external_lex_state = 4},
  [19] = {.lex_state = 0, .external_lex_state = 4},
  [20] = {.lex_state = 7, .external_lex_state = 5},
  [21] = {.lex_state = 7, .external_lex_state = 5},
  [22] = {.lex_state = 0, .external_lex_state = 4},
  [23] = {.lex_state = 7, .external_lex_state = 5},
  [24] = {.lex_state = 7, .external_lex_state = 5},
  [25] = {.lex_state = 7, .external_lex_state = 5},
  [26] = {.lex_state = 29},
  [27] = {.lex_state = 29},
  [28] = {.lex_state = 7, .external_lex_state = 5},
  [29] = {.lex_state = 29},
  [30] = {.lex_state = 0, .external_lex_state = 4},
  [31] = {.lex_state = 0, .external_lex_state = 4},
  [32] = {.lex_state = 29},
  [33] = {.lex_state = 0, .external_lex_state = 4},
  [34] = {.lex_state = 29},
  [35] = {.lex_state = 0, .external_lex_state = 4},
  [36] = {.lex_state = 0, .external_lex_state = 4},
  [37] = {.lex_state = 0, .external_lex_state = 4},
  [38] = {.lex_state = 29},
  [39] = {.lex_state = 29, .external_lex_state = 2},
  [40] = {.lex_state = 29, .external_lex_state = 2},
  [41] = {.lex_state = 29},
  [42] = {.lex_state = 29, .external_lex_state = 2},
  [43] = {.lex_state = 29, .external_lex_state = 2},
  [44] = {.lex_state = 29},
  [45] = {.lex_state = 29, .external_lex_state = 2},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 29},
  [48] = {.lex_state = 29, .external_lex_state = 2},
  [49] = {.lex_state = 29, .external_lex_state = 2},
  [50] = {.lex_state = 29, .external_lex_state = 2},
  [51] = {.lex_state = 29},
  [52] = {.lex_state = 29, .external_lex_state = 2},
  [53] = {.lex_state = 29},
  [54] = {.lex_state = 29, .external_lex_state = 2},
  [55] = {.lex_state = 29},
  [56] = {.lex_state = 29},
  [57] = {.lex_state = 29},
  [58] = {.lex_state = 29},
  [59] = {.lex_state = 29},
  [60] = {.lex_state = 29},
  [61] = {.lex_state = 29, .external_lex_state = 2},
  [62] = {.lex_state = 29, .external_lex_state = 2},
  [63] = {.lex_state = 29},
  [64] = {.lex_state = 29, .external_lex_state = 2},
  [65] = {.lex_state = 29},
  [66] = {.lex_state = 29, .external_lex_state = 2},
  [67] = {.lex_state = 29, .external_lex_state = 2},
  [68] = {.lex_state = 29, .external_lex_state = 2},
  [69] = {.lex_state = 29, .external_lex_state = 2},
  [70] = {.lex_state = 29, .external_lex_state = 2},
  [71] = {.lex_state = 29, .external_lex_state = 2},
  [72] = {.lex_state = 29, .external_lex_state = 2},
  [73] = {.lex_state = 29, .external_lex_state = 2},
  [74] = {.lex_state = 29},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 1},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 1},
  [92] = {.lex_state = 0, .external_lex_state = 3},
  [93] = {.lex_state = 0, .external_lex_state = 4},
  [94] = {.lex_state = 0, .external_lex_state = 3},
  [95] = {.lex_state = 0, .external_lex_state = 3},
  [96] = {.lex_state = 0, .external_lex_state = 3},
  [97] = {.lex_state = 0, .external_lex_state = 3},
  [98] = {.lex_state = 0, .external_lex_state = 3},
  [99] = {.lex_state = 0, .external_lex_state = 3},
  [100] = {.lex_state = 1},
  [101] = {.lex_state = 1},
  [102] = {.lex_state = 1},
  [103] = {.lex_state = 1},
  [104] = {.lex_state = 1},
  [105] = {.lex_state = 0, .external_lex_state = 4},
  [106] = {.lex_state = 1},
  [107] = {.lex_state = 0, .external_lex_state = 4},
  [108] = {.lex_state = 0, .external_lex_state = 4},
  [109] = {.lex_state = 1},
  [110] = {.lex_state = 0, .external_lex_state = 4},
  [111] = {.lex_state = 1},
  [112] = {.lex_state = 1},
  [113] = {.lex_state = 1},
  [114] = {.lex_state = 0, .external_lex_state = 4},
  [115] = {.lex_state = 1},
  [116] = {.lex_state = 7, .external_lex_state = 5},
  [117] = {.lex_state = 1},
  [118] = {.lex_state = 1},
  [119] = {.lex_state = 1},
  [120] = {.lex_state = 1},
  [121] = {.lex_state = 0, .external_lex_state = 3},
  [122] = {.lex_state = 0, .external_lex_state = 4},
  [123] = {.lex_state = 1},
  [124] = {.lex_state = 1},
  [125] = {.lex_state = 0, .external_lex_state = 4},
  [126] = {.lex_state = 0, .external_lex_state = 3},
  [127] = {.lex_state = 1},
  [128] = {.lex_state = 0, .external_lex_state = 5},
  [129] = {.lex_state = 0, .external_lex_state = 5},
  [130] = {.lex_state = 0, .external_lex_state = 5},
  [131] = {.lex_state = 0, .external_lex_state = 5},
  [132] = {.lex_state = 0, .external_lex_state = 5},
  [133] = {.lex_state = 0, .external_lex_state = 5},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0, .external_lex_state = 6},
  [136] = {.lex_state = 0},
};

enum {
  ts_external_token__newline = 0,
  ts_external_token__indent = 1,
  ts_external_token__dedent = 2,
  ts_external_token__string_start = 3,
  ts_external_token__string_content = 4,
  ts_external_token__string_end = 5,
  ts_external_token__comment = 6,
  ts_external_token_RBRACK = 7,
  ts_external_token_RPAREN = 8,
  ts_external_token_RBRACE = 9,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token__indent] = sym__indent,
  [ts_external_token__dedent] = sym__dedent,
  [ts_external_token__string_start] = sym__string_start,
  [ts_external_token__string_content] = sym__string_content,
  [ts_external_token__string_end] = sym__string_end,
  [ts_external_token__comment] = sym__comment,
  [ts_external_token_RBRACK] = anon_sym_RBRACK,
  [ts_external_token_RPAREN] = anon_sym_RPAREN,
  [ts_external_token_RBRACE] = anon_sym_RBRACE,
};

static const bool ts_external_scanner_states[7][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token__indent] = true,
    [ts_external_token__dedent] = true,
    [ts_external_token__string_start] = true,
    [ts_external_token__string_content] = true,
    [ts_external_token__string_end] = true,
    [ts_external_token__comment] = true,
    [ts_external_token_RBRACK] = true,
    [ts_external_token_RPAREN] = true,
    [ts_external_token_RBRACE] = true,
  },
  [2] = {
    [ts_external_token__dedent] = true,
  },
  [3] = {
    [ts_external_token_RBRACE] = true,
  },
  [4] = {
    [ts_external_token_RBRACK] = true,
  },
  [5] = {
    [ts_external_token__newline] = true,
  },
  [6] = {
    [ts_external_token__indent] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_STARsave_COLON] = ACTIONS(1),
    [anon_sym_STARif_COLON] = ACTIONS(1),
    [anon_sym_STARwhile_COLON] = ACTIONS(1),
    [anon_sym_STARfor_COLON] = ACTIONS(1),
    [anon_sym_STARquestion_COLON] = ACTIONS(1),
    [anon_sym_GT_GT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_comma_divider] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [sym_lessThan_operator] = ACTIONS(1),
    [sym_moreThan_operator] = ACTIONS(1),
    [sym_in_operator] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym__dedent] = ACTIONS(1),
    [sym__string_start] = ACTIONS(1),
    [sym__string_content] = ACTIONS(1),
    [sym__string_end] = ACTIONS(1),
    [sym__comment] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(136),
    [sym__definition] = STATE(6),
    [sym__command_definition] = STATE(6),
    [sym_save_command_definition] = STATE(6),
    [sym__function_definition] = STATE(6),
    [sym_if_function_definition] = STATE(6),
    [sym_while_function_definition] = STATE(6),
    [sym_for_function_definition] = STATE(6),
    [sym_question_function_definition] = STATE(6),
    [sym_variable_definition] = STATE(6),
    [sym__keyword_definition] = STATE(6),
    [sym_plain_text] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_STARsave_COLON] = ACTIONS(5),
    [anon_sym_STARif_COLON] = ACTIONS(7),
    [anon_sym_STARwhile_COLON] = ACTIONS(9),
    [anon_sym_STARfor_COLON] = ACTIONS(11),
    [anon_sym_STARquestion_COLON] = ACTIONS(13),
    [anon_sym_GT_GT] = ACTIONS(15),
    [aux_sym_identifier_token1] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(19), 1,
      anon_sym_STARsave_COLON,
    ACTIONS(21), 1,
      anon_sym_STARif_COLON,
    ACTIONS(23), 1,
      anon_sym_STARwhile_COLON,
    ACTIONS(25), 1,
      anon_sym_STARfor_COLON,
    ACTIONS(27), 1,
      anon_sym_STARquestion_COLON,
    ACTIONS(29), 1,
      anon_sym_GT_GT,
    ACTIONS(31), 1,
      aux_sym_identifier_token1,
    ACTIONS(33), 1,
      sym__dedent,
    STATE(73), 1,
      sym__block_end,
    STATE(4), 12,
      sym__definition,
      sym__command_definition,
      sym_save_command_definition,
      sym__function_definition,
      sym_if_function_definition,
      sym_while_function_definition,
      sym_for_function_definition,
      sym_question_function_definition,
      sym_variable_definition,
      sym__keyword_definition,
      sym_plain_text,
      aux_sym_source_file_repeat1,
  [42] = 10,
    ACTIONS(19), 1,
      anon_sym_STARsave_COLON,
    ACTIONS(21), 1,
      anon_sym_STARif_COLON,
    ACTIONS(23), 1,
      anon_sym_STARwhile_COLON,
    ACTIONS(25), 1,
      anon_sym_STARfor_COLON,
    ACTIONS(27), 1,
      anon_sym_STARquestion_COLON,
    ACTIONS(29), 1,
      anon_sym_GT_GT,
    ACTIONS(31), 1,
      aux_sym_identifier_token1,
    ACTIONS(35), 1,
      sym__dedent,
    STATE(56), 1,
      sym__block_end,
    STATE(7), 12,
      sym__definition,
      sym__command_definition,
      sym_save_command_definition,
      sym__function_definition,
      sym_if_function_definition,
      sym_while_function_definition,
      sym_for_function_definition,
      sym_question_function_definition,
      sym_variable_definition,
      sym__keyword_definition,
      sym_plain_text,
      aux_sym_source_file_repeat1,
  [84] = 10,
    ACTIONS(19), 1,
      anon_sym_STARsave_COLON,
    ACTIONS(21), 1,
      anon_sym_STARif_COLON,
    ACTIONS(23), 1,
      anon_sym_STARwhile_COLON,
    ACTIONS(25), 1,
      anon_sym_STARfor_COLON,
    ACTIONS(27), 1,
      anon_sym_STARquestion_COLON,
    ACTIONS(29), 1,
      anon_sym_GT_GT,
    ACTIONS(31), 1,
      aux_sym_identifier_token1,
    ACTIONS(37), 1,
      sym__dedent,
    STATE(40), 1,
      sym__block_end,
    STATE(7), 12,
      sym__definition,
      sym__command_definition,
      sym_save_command_definition,
      sym__function_definition,
      sym_if_function_definition,
      sym_while_function_definition,
      sym_for_function_definition,
      sym_question_function_definition,
      sym_variable_definition,
      sym__keyword_definition,
      sym_plain_text,
      aux_sym_source_file_repeat1,
  [126] = 10,
    ACTIONS(19), 1,
      anon_sym_STARsave_COLON,
    ACTIONS(21), 1,
      anon_sym_STARif_COLON,
    ACTIONS(23), 1,
      anon_sym_STARwhile_COLON,
    ACTIONS(25), 1,
      anon_sym_STARfor_COLON,
    ACTIONS(27), 1,
      anon_sym_STARquestion_COLON,
    ACTIONS(29), 1,
      anon_sym_GT_GT,
    ACTIONS(31), 1,
      aux_sym_identifier_token1,
    ACTIONS(39), 1,
      sym__dedent,
    STATE(47), 1,
      sym__block_end,
    STATE(3), 12,
      sym__definition,
      sym__command_definition,
      sym_save_command_definition,
      sym__function_definition,
      sym_if_function_definition,
      sym_while_function_definition,
      sym_for_function_definition,
      sym_question_function_definition,
      sym_variable_definition,
      sym__keyword_definition,
      sym_plain_text,
      aux_sym_source_file_repeat1,
  [168] = 9,
    ACTIONS(5), 1,
      anon_sym_STARsave_COLON,
    ACTIONS(7), 1,
      anon_sym_STARif_COLON,
    ACTIONS(9), 1,
      anon_sym_STARwhile_COLON,
    ACTIONS(11), 1,
      anon_sym_STARfor_COLON,
    ACTIONS(13), 1,
      anon_sym_STARquestion_COLON,
    ACTIONS(15), 1,
      anon_sym_GT_GT,
    ACTIONS(17), 1,
      aux_sym_identifier_token1,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    STATE(8), 12,
      sym__definition,
      sym__command_definition,
      sym_save_command_definition,
      sym__function_definition,
      sym_if_function_definition,
      sym_while_function_definition,
      sym_for_function_definition,
      sym_question_function_definition,
      sym_variable_definition,
      sym__keyword_definition,
      sym_plain_text,
      aux_sym_source_file_repeat1,
  [207] = 9,
    ACTIONS(43), 1,
      anon_sym_STARsave_COLON,
    ACTIONS(46), 1,
      anon_sym_STARif_COLON,
    ACTIONS(49), 1,
      anon_sym_STARwhile_COLON,
    ACTIONS(52), 1,
      anon_sym_STARfor_COLON,
    ACTIONS(55), 1,
      anon_sym_STARquestion_COLON,
    ACTIONS(58), 1,
      anon_sym_GT_GT,
    ACTIONS(61), 1,
      aux_sym_identifier_token1,
    ACTIONS(64), 1,
      sym__dedent,
    STATE(7), 12,
      sym__definition,
      sym__command_definition,
      sym_save_command_definition,
      sym__function_definition,
      sym_if_function_definition,
      sym_while_function_definition,
      sym_for_function_definition,
      sym_question_function_definition,
      sym_variable_definition,
      sym__keyword_definition,
      sym_plain_text,
      aux_sym_source_file_repeat1,
  [246] = 9,
    ACTIONS(64), 1,
      ts_builtin_sym_end,
    ACTIONS(66), 1,
      anon_sym_STARsave_COLON,
    ACTIONS(69), 1,
      anon_sym_STARif_COLON,
    ACTIONS(72), 1,
      anon_sym_STARwhile_COLON,
    ACTIONS(75), 1,
      anon_sym_STARfor_COLON,
    ACTIONS(78), 1,
      anon_sym_STARquestion_COLON,
    ACTIONS(81), 1,
      anon_sym_GT_GT,
    ACTIONS(84), 1,
      aux_sym_identifier_token1,
    STATE(8), 12,
      sym__definition,
      sym__command_definition,
      sym_save_command_definition,
      sym__function_definition,
      sym_if_function_definition,
      sym_while_function_definition,
      sym_for_function_definition,
      sym_question_function_definition,
      sym_variable_definition,
      sym__keyword_definition,
      sym_plain_text,
      aux_sym_source_file_repeat1,
  [285] = 7,
    ACTIONS(87), 1,
      anon_sym_DQUOTE,
    ACTIONS(89), 1,
      anon_sym_LBRACK,
    ACTIONS(91), 1,
      anon_sym_LBRACE,
    ACTIONS(93), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_dictionary_type_repeat1,
    STATE(121), 1,
      sym_dictionary_pair,
    STATE(134), 4,
      sym__type,
      sym_string_type,
      sym_array_type,
      sym_dictionary_type,
  [310] = 7,
    ACTIONS(87), 1,
      anon_sym_DQUOTE,
    ACTIONS(89), 1,
      anon_sym_LBRACK,
    ACTIONS(91), 1,
      anon_sym_LBRACE,
    ACTIONS(95), 1,
      anon_sym_RBRACE,
    STATE(9), 1,
      aux_sym_dictionary_type_repeat1,
    STATE(121), 1,
      sym_dictionary_pair,
    STATE(134), 4,
      sym__type,
      sym_string_type,
      sym_array_type,
      sym_dictionary_type,
  [335] = 7,
    ACTIONS(87), 1,
      anon_sym_DQUOTE,
    ACTIONS(89), 1,
      anon_sym_LBRACK,
    ACTIONS(91), 1,
      anon_sym_LBRACE,
    ACTIONS(97), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_dictionary_type_repeat1,
    STATE(121), 1,
      sym_dictionary_pair,
    STATE(134), 4,
      sym__type,
      sym_string_type,
      sym_array_type,
      sym_dictionary_type,
  [360] = 7,
    ACTIONS(87), 1,
      anon_sym_DQUOTE,
    ACTIONS(89), 1,
      anon_sym_LBRACK,
    ACTIONS(91), 1,
      anon_sym_LBRACE,
    ACTIONS(99), 1,
      anon_sym_RBRACE,
    STATE(14), 1,
      aux_sym_dictionary_type_repeat1,
    STATE(121), 1,
      sym_dictionary_pair,
    STATE(134), 4,
      sym__type,
      sym_string_type,
      sym_array_type,
      sym_dictionary_type,
  [385] = 7,
    ACTIONS(87), 1,
      anon_sym_DQUOTE,
    ACTIONS(89), 1,
      anon_sym_LBRACK,
    ACTIONS(91), 1,
      anon_sym_LBRACE,
    ACTIONS(101), 1,
      anon_sym_RBRACE,
    STATE(11), 1,
      aux_sym_dictionary_type_repeat1,
    STATE(121), 1,
      sym_dictionary_pair,
    STATE(134), 4,
      sym__type,
      sym_string_type,
      sym_array_type,
      sym_dictionary_type,
  [410] = 7,
    ACTIONS(87), 1,
      anon_sym_DQUOTE,
    ACTIONS(89), 1,
      anon_sym_LBRACK,
    ACTIONS(91), 1,
      anon_sym_LBRACE,
    ACTIONS(103), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_dictionary_type_repeat1,
    STATE(121), 1,
      sym_dictionary_pair,
    STATE(134), 4,
      sym__type,
      sym_string_type,
      sym_array_type,
      sym_dictionary_type,
  [435] = 7,
    ACTIONS(87), 1,
      anon_sym_DQUOTE,
    ACTIONS(89), 1,
      anon_sym_LBRACK,
    ACTIONS(91), 1,
      anon_sym_LBRACE,
    ACTIONS(105), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_dictionary_type_repeat1,
    STATE(121), 1,
      sym_dictionary_pair,
    STATE(134), 4,
      sym__type,
      sym_string_type,
      sym_array_type,
      sym_dictionary_type,
  [460] = 7,
    ACTIONS(107), 1,
      anon_sym_DQUOTE,
    ACTIONS(110), 1,
      anon_sym_LBRACK,
    ACTIONS(113), 1,
      anon_sym_LBRACE,
    ACTIONS(116), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      aux_sym_dictionary_type_repeat1,
    STATE(121), 1,
      sym_dictionary_pair,
    STATE(134), 4,
      sym__type,
      sym_string_type,
      sym_array_type,
      sym_dictionary_type,
  [485] = 7,
    ACTIONS(87), 1,
      anon_sym_DQUOTE,
    ACTIONS(89), 1,
      anon_sym_LBRACK,
    ACTIONS(91), 1,
      anon_sym_LBRACE,
    ACTIONS(118), 1,
      anon_sym_RBRACE,
    STATE(15), 1,
      aux_sym_dictionary_type_repeat1,
    STATE(121), 1,
      sym_dictionary_pair,
    STATE(134), 4,
      sym__type,
      sym_string_type,
      sym_array_type,
      sym_dictionary_type,
  [510] = 6,
    ACTIONS(120), 1,
      anon_sym_DQUOTE,
    ACTIONS(122), 1,
      anon_sym_LBRACK,
    ACTIONS(124), 1,
      anon_sym_RBRACK,
    ACTIONS(126), 1,
      anon_sym_LBRACE,
    STATE(35), 1,
      aux_sym_array_type_repeat1,
    STATE(122), 4,
      sym__type,
      sym_string_type,
      sym_array_type,
      sym_dictionary_type,
  [532] = 6,
    ACTIONS(120), 1,
      anon_sym_DQUOTE,
    ACTIONS(122), 1,
      anon_sym_LBRACK,
    ACTIONS(126), 1,
      anon_sym_LBRACE,
    ACTIONS(128), 1,
      anon_sym_RBRACK,
    STATE(31), 1,
      aux_sym_array_type_repeat1,
    STATE(122), 4,
      sym__type,
      sym_string_type,
      sym_array_type,
      sym_dictionary_type,
  [554] = 6,
    ACTIONS(130), 1,
      anon_sym_EQ,
    ACTIONS(134), 1,
      sym__newline,
    STATE(2), 1,
      sym__block_start,
    STATE(71), 1,
      sym_block,
    STATE(106), 2,
      sym__operator,
      sym_equal_operator,
    ACTIONS(132), 3,
      sym_lessThan_operator,
      sym_moreThan_operator,
      sym_in_operator,
  [576] = 6,
    ACTIONS(130), 1,
      anon_sym_EQ,
    ACTIONS(134), 1,
      sym__newline,
    STATE(2), 1,
      sym__block_start,
    STATE(70), 1,
      sym_block,
    STATE(111), 2,
      sym__operator,
      sym_equal_operator,
    ACTIONS(136), 3,
      sym_lessThan_operator,
      sym_moreThan_operator,
      sym_in_operator,
  [598] = 6,
    ACTIONS(120), 1,
      anon_sym_DQUOTE,
    ACTIONS(122), 1,
      anon_sym_LBRACK,
    ACTIONS(126), 1,
      anon_sym_LBRACE,
    ACTIONS(138), 1,
      anon_sym_RBRACK,
    STATE(36), 1,
      aux_sym_array_type_repeat1,
    STATE(122), 4,
      sym__type,
      sym_string_type,
      sym_array_type,
      sym_dictionary_type,
  [620] = 6,
    ACTIONS(130), 1,
      anon_sym_EQ,
    ACTIONS(134), 1,
      sym__newline,
    STATE(2), 1,
      sym__block_start,
    STATE(69), 1,
      sym_block,
    STATE(112), 2,
      sym__operator,
      sym_equal_operator,
    ACTIONS(140), 3,
      sym_lessThan_operator,
      sym_moreThan_operator,
      sym_in_operator,
  [642] = 6,
    ACTIONS(130), 1,
      anon_sym_EQ,
    ACTIONS(134), 1,
      sym__newline,
    STATE(5), 1,
      sym__block_start,
    STATE(41), 1,
      sym_block,
    STATE(104), 2,
      sym__operator,
      sym_equal_operator,
    ACTIONS(142), 3,
      sym_lessThan_operator,
      sym_moreThan_operator,
      sym_in_operator,
  [664] = 6,
    ACTIONS(130), 1,
      anon_sym_EQ,
    ACTIONS(134), 1,
      sym__newline,
    STATE(5), 1,
      sym__block_start,
    STATE(74), 1,
      sym_block,
    STATE(117), 2,
      sym__operator,
      sym_equal_operator,
    ACTIONS(144), 3,
      sym_lessThan_operator,
      sym_moreThan_operator,
      sym_in_operator,
  [686] = 1,
    ACTIONS(146), 9,
      ts_builtin_sym_end,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      anon_sym_DASH_GT,
      aux_sym_identifier_token1,
  [698] = 1,
    ACTIONS(148), 9,
      ts_builtin_sym_end,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      anon_sym_DASH_GT,
      aux_sym_identifier_token1,
  [710] = 6,
    ACTIONS(130), 1,
      anon_sym_EQ,
    ACTIONS(134), 1,
      sym__newline,
    STATE(5), 1,
      sym__block_start,
    STATE(51), 1,
      sym_block,
    STATE(102), 2,
      sym__operator,
      sym_equal_operator,
    ACTIONS(150), 3,
      sym_lessThan_operator,
      sym_moreThan_operator,
      sym_in_operator,
  [732] = 1,
    ACTIONS(152), 9,
      ts_builtin_sym_end,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      anon_sym_DASH_GT,
      aux_sym_identifier_token1,
  [744] = 6,
    ACTIONS(120), 1,
      anon_sym_DQUOTE,
    ACTIONS(122), 1,
      anon_sym_LBRACK,
    ACTIONS(126), 1,
      anon_sym_LBRACE,
    ACTIONS(154), 1,
      anon_sym_RBRACK,
    STATE(33), 1,
      aux_sym_array_type_repeat1,
    STATE(122), 4,
      sym__type,
      sym_string_type,
      sym_array_type,
      sym_dictionary_type,
  [766] = 6,
    ACTIONS(120), 1,
      anon_sym_DQUOTE,
    ACTIONS(122), 1,
      anon_sym_LBRACK,
    ACTIONS(126), 1,
      anon_sym_LBRACE,
    ACTIONS(156), 1,
      anon_sym_RBRACK,
    STATE(36), 1,
      aux_sym_array_type_repeat1,
    STATE(122), 4,
      sym__type,
      sym_string_type,
      sym_array_type,
      sym_dictionary_type,
  [788] = 1,
    ACTIONS(158), 9,
      ts_builtin_sym_end,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      anon_sym_DASH_GT,
      aux_sym_identifier_token1,
  [800] = 6,
    ACTIONS(120), 1,
      anon_sym_DQUOTE,
    ACTIONS(122), 1,
      anon_sym_LBRACK,
    ACTIONS(126), 1,
      anon_sym_LBRACE,
    ACTIONS(160), 1,
      anon_sym_RBRACK,
    STATE(36), 1,
      aux_sym_array_type_repeat1,
    STATE(122), 4,
      sym__type,
      sym_string_type,
      sym_array_type,
      sym_dictionary_type,
  [822] = 1,
    ACTIONS(162), 9,
      ts_builtin_sym_end,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      anon_sym_DASH_GT,
      aux_sym_identifier_token1,
  [834] = 6,
    ACTIONS(120), 1,
      anon_sym_DQUOTE,
    ACTIONS(122), 1,
      anon_sym_LBRACK,
    ACTIONS(126), 1,
      anon_sym_LBRACE,
    ACTIONS(164), 1,
      anon_sym_RBRACK,
    STATE(36), 1,
      aux_sym_array_type_repeat1,
    STATE(122), 4,
      sym__type,
      sym_string_type,
      sym_array_type,
      sym_dictionary_type,
  [856] = 6,
    ACTIONS(166), 1,
      anon_sym_DQUOTE,
    ACTIONS(169), 1,
      anon_sym_LBRACK,
    ACTIONS(172), 1,
      anon_sym_RBRACK,
    ACTIONS(174), 1,
      anon_sym_LBRACE,
    STATE(36), 1,
      aux_sym_array_type_repeat1,
    STATE(122), 4,
      sym__type,
      sym_string_type,
      sym_array_type,
      sym_dictionary_type,
  [878] = 6,
    ACTIONS(120), 1,
      anon_sym_DQUOTE,
    ACTIONS(122), 1,
      anon_sym_LBRACK,
    ACTIONS(126), 1,
      anon_sym_LBRACE,
    ACTIONS(177), 1,
      anon_sym_RBRACK,
    STATE(22), 1,
      aux_sym_array_type_repeat1,
    STATE(122), 4,
      sym__type,
      sym_string_type,
      sym_array_type,
      sym_dictionary_type,
  [900] = 1,
    ACTIONS(179), 9,
      ts_builtin_sym_end,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      anon_sym_DASH_GT,
      aux_sym_identifier_token1,
  [912] = 1,
    ACTIONS(181), 8,
      sym__dedent,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [923] = 1,
    ACTIONS(183), 8,
      sym__dedent,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [934] = 1,
    ACTIONS(185), 8,
      ts_builtin_sym_end,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [945] = 1,
    ACTIONS(158), 8,
      sym__dedent,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [956] = 1,
    ACTIONS(146), 8,
      sym__dedent,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [967] = 1,
    ACTIONS(187), 8,
      ts_builtin_sym_end,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [978] = 1,
    ACTIONS(162), 8,
      sym__dedent,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [989] = 5,
    ACTIONS(191), 1,
      aux_sym_identifier_token1,
    ACTIONS(194), 1,
      sym_question,
    ACTIONS(197), 1,
      sym_number,
    ACTIONS(189), 2,
      anon_sym_EQ,
      anon_sym_DQUOTE,
    STATE(46), 3,
      sym__expression,
      sym_identifier,
      aux_sym_variable_definition_repeat1,
  [1008] = 1,
    ACTIONS(200), 8,
      ts_builtin_sym_end,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [1019] = 1,
    ACTIONS(152), 8,
      sym__dedent,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [1030] = 1,
    ACTIONS(148), 8,
      sym__dedent,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [1041] = 1,
    ACTIONS(202), 8,
      sym__dedent,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [1052] = 1,
    ACTIONS(204), 8,
      ts_builtin_sym_end,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [1063] = 1,
    ACTIONS(206), 8,
      sym__dedent,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [1074] = 1,
    ACTIONS(208), 8,
      ts_builtin_sym_end,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [1085] = 1,
    ACTIONS(210), 8,
      sym__dedent,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [1096] = 1,
    ACTIONS(212), 8,
      ts_builtin_sym_end,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [1107] = 1,
    ACTIONS(183), 8,
      ts_builtin_sym_end,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [1118] = 1,
    ACTIONS(214), 8,
      ts_builtin_sym_end,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [1129] = 1,
    ACTIONS(210), 8,
      ts_builtin_sym_end,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [1140] = 1,
    ACTIONS(206), 8,
      ts_builtin_sym_end,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [1151] = 1,
    ACTIONS(202), 8,
      ts_builtin_sym_end,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [1162] = 1,
    ACTIONS(214), 8,
      sym__dedent,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [1173] = 1,
    ACTIONS(179), 8,
      sym__dedent,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [1184] = 1,
    ACTIONS(216), 8,
      ts_builtin_sym_end,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [1195] = 1,
    ACTIONS(208), 8,
      sym__dedent,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [1206] = 1,
    ACTIONS(218), 8,
      ts_builtin_sym_end,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [1217] = 1,
    ACTIONS(216), 8,
      sym__dedent,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [1228] = 1,
    ACTIONS(218), 8,
      sym__dedent,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [1239] = 1,
    ACTIONS(212), 8,
      sym__dedent,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [1250] = 1,
    ACTIONS(204), 8,
      sym__dedent,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [1261] = 1,
    ACTIONS(220), 8,
      sym__dedent,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [1272] = 1,
    ACTIONS(185), 8,
      sym__dedent,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [1283] = 1,
    ACTIONS(187), 8,
      sym__dedent,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [1294] = 1,
    ACTIONS(200), 8,
      sym__dedent,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [1305] = 1,
    ACTIONS(220), 8,
      ts_builtin_sym_end,
      anon_sym_STARsave_COLON,
      anon_sym_STARif_COLON,
      anon_sym_STARwhile_COLON,
      anon_sym_STARfor_COLON,
      anon_sym_STARquestion_COLON,
      anon_sym_GT_GT,
      aux_sym_identifier_token1,
  [1316] = 4,
    ACTIONS(222), 1,
      anon_sym_DQUOTE,
    ACTIONS(224), 1,
      anon_sym_LBRACK,
    ACTIONS(226), 1,
      anon_sym_LBRACE,
    STATE(68), 4,
      sym__type,
      sym_string_type,
      sym_array_type,
      sym_dictionary_type,
  [1332] = 4,
    ACTIONS(87), 1,
      anon_sym_DQUOTE,
    ACTIONS(89), 1,
      anon_sym_LBRACK,
    ACTIONS(91), 1,
      anon_sym_LBRACE,
    STATE(44), 4,
      sym__type,
      sym_string_type,
      sym_array_type,
      sym_dictionary_type,
  [1348] = 5,
    ACTIONS(228), 1,
      anon_sym_EQ,
    ACTIONS(230), 1,
      aux_sym_identifier_token1,
    ACTIONS(232), 1,
      sym_question,
    ACTIONS(234), 1,
      sym_number,
    STATE(46), 3,
      sym__expression,
      sym_identifier,
      aux_sym_variable_definition_repeat1,
  [1366] = 5,
    ACTIONS(230), 1,
      aux_sym_identifier_token1,
    ACTIONS(232), 1,
      sym_question,
    ACTIONS(234), 1,
      sym_number,
    ACTIONS(236), 1,
      anon_sym_DQUOTE,
    STATE(46), 3,
      sym__expression,
      sym_identifier,
      aux_sym_variable_definition_repeat1,
  [1384] = 5,
    ACTIONS(230), 1,
      aux_sym_identifier_token1,
    ACTIONS(238), 1,
      anon_sym_DQUOTE,
    ACTIONS(240), 1,
      sym_question,
    ACTIONS(242), 1,
      sym_number,
    STATE(81), 3,
      sym__expression,
      sym_identifier,
      aux_sym_variable_definition_repeat1,
  [1402] = 4,
    ACTIONS(244), 1,
      anon_sym_DQUOTE,
    ACTIONS(246), 1,
      anon_sym_LBRACK,
    ACTIONS(248), 1,
      anon_sym_LBRACE,
    STATE(92), 4,
      sym__type,
      sym_string_type,
      sym_array_type,
      sym_dictionary_type,
  [1418] = 5,
    ACTIONS(230), 1,
      aux_sym_identifier_token1,
    ACTIONS(232), 1,
      sym_question,
    ACTIONS(234), 1,
      sym_number,
    ACTIONS(250), 1,
      anon_sym_DQUOTE,
    STATE(46), 3,
      sym__expression,
      sym_identifier,
      aux_sym_variable_definition_repeat1,
  [1436] = 5,
    ACTIONS(230), 1,
      aux_sym_identifier_token1,
    ACTIONS(252), 1,
      anon_sym_EQ,
    ACTIONS(254), 1,
      sym_question,
    ACTIONS(256), 1,
      sym_number,
    STATE(77), 3,
      sym__expression,
      sym_identifier,
      aux_sym_variable_definition_repeat1,
  [1454] = 5,
    ACTIONS(230), 1,
      aux_sym_identifier_token1,
    ACTIONS(258), 1,
      anon_sym_DQUOTE,
    ACTIONS(260), 1,
      sym_question,
    ACTIONS(262), 1,
      sym_number,
    STATE(78), 3,
      sym__expression,
      sym_identifier,
      aux_sym_variable_definition_repeat1,
  [1472] = 4,
    ACTIONS(222), 1,
      anon_sym_DQUOTE,
    ACTIONS(224), 1,
      anon_sym_LBRACK,
    ACTIONS(226), 1,
      anon_sym_LBRACE,
    STATE(72), 4,
      sym__type,
      sym_string_type,
      sym_array_type,
      sym_dictionary_type,
  [1488] = 5,
    ACTIONS(230), 1,
      aux_sym_identifier_token1,
    ACTIONS(232), 1,
      sym_question,
    ACTIONS(234), 1,
      sym_number,
    ACTIONS(264), 1,
      anon_sym_DQUOTE,
    STATE(46), 3,
      sym__expression,
      sym_identifier,
      aux_sym_variable_definition_repeat1,
  [1506] = 5,
    ACTIONS(230), 1,
      aux_sym_identifier_token1,
    ACTIONS(266), 1,
      anon_sym_DQUOTE,
    ACTIONS(268), 1,
      sym_question,
    ACTIONS(270), 1,
      sym_number,
    STATE(87), 3,
      sym__expression,
      sym_identifier,
      aux_sym_variable_definition_repeat1,
  [1524] = 5,
    ACTIONS(230), 1,
      aux_sym_identifier_token1,
    ACTIONS(232), 1,
      sym_question,
    ACTIONS(234), 1,
      sym_number,
    ACTIONS(272), 1,
      anon_sym_DQUOTE,
    STATE(46), 3,
      sym__expression,
      sym_identifier,
      aux_sym_variable_definition_repeat1,
  [1542] = 5,
    ACTIONS(230), 1,
      aux_sym_identifier_token1,
    ACTIONS(274), 1,
      anon_sym_EQ,
    ACTIONS(276), 1,
      sym_question,
    ACTIONS(278), 1,
      sym_number,
    STATE(91), 3,
      sym__expression,
      sym_identifier,
      aux_sym_variable_definition_repeat1,
  [1560] = 4,
    ACTIONS(87), 1,
      anon_sym_DQUOTE,
    ACTIONS(89), 1,
      anon_sym_LBRACK,
    ACTIONS(91), 1,
      anon_sym_LBRACE,
    STATE(55), 4,
      sym__type,
      sym_string_type,
      sym_array_type,
      sym_dictionary_type,
  [1576] = 5,
    ACTIONS(230), 1,
      aux_sym_identifier_token1,
    ACTIONS(280), 1,
      anon_sym_DQUOTE,
    ACTIONS(282), 1,
      sym_question,
    ACTIONS(284), 1,
      sym_number,
    STATE(85), 3,
      sym__expression,
      sym_identifier,
      aux_sym_variable_definition_repeat1,
  [1594] = 5,
    ACTIONS(230), 1,
      aux_sym_identifier_token1,
    ACTIONS(232), 1,
      sym_question,
    ACTIONS(234), 1,
      sym_number,
    ACTIONS(286), 1,
      anon_sym_EQ,
    STATE(46), 3,
      sym__expression,
      sym_identifier,
      aux_sym_variable_definition_repeat1,
  [1612] = 1,
    ACTIONS(288), 5,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_comma_divider,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1620] = 1,
    ACTIONS(162), 5,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_comma_divider,
      anon_sym_LBRACE,
  [1628] = 1,
    ACTIONS(148), 5,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_comma_divider,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1636] = 1,
    ACTIONS(152), 5,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_comma_divider,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1644] = 1,
    ACTIONS(162), 5,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_comma_divider,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1652] = 1,
    ACTIONS(146), 5,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_comma_divider,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1660] = 1,
    ACTIONS(158), 5,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_comma_divider,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1668] = 1,
    ACTIONS(179), 5,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_comma_divider,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1676] = 4,
    ACTIONS(290), 1,
      aux_sym_identifier_token1,
    ACTIONS(292), 1,
      sym_question,
    ACTIONS(294), 1,
      sym_number,
    STATE(66), 2,
      sym__expression,
      sym_identifier,
  [1690] = 4,
    ACTIONS(290), 1,
      aux_sym_identifier_token1,
    ACTIONS(296), 1,
      sym_question,
    ACTIONS(298), 1,
      sym_number,
    STATE(67), 2,
      sym__expression,
      sym_identifier,
  [1704] = 4,
    ACTIONS(300), 1,
      aux_sym_identifier_token1,
    ACTIONS(302), 1,
      sym_question,
    ACTIONS(304), 1,
      sym_number,
    STATE(130), 2,
      sym__expression,
      sym_identifier,
  [1718] = 2,
    ACTIONS(306), 2,
      aux_sym_identifier_token1,
      sym_question,
    ACTIONS(202), 3,
      anon_sym_EQ,
      anon_sym_DQUOTE,
      sym_number,
  [1728] = 4,
    ACTIONS(300), 1,
      aux_sym_identifier_token1,
    ACTIONS(308), 1,
      sym_question,
    ACTIONS(310), 1,
      sym_number,
    STATE(128), 2,
      sym__expression,
      sym_identifier,
  [1742] = 1,
    ACTIONS(179), 5,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_comma_divider,
      anon_sym_LBRACE,
  [1750] = 4,
    ACTIONS(300), 1,
      aux_sym_identifier_token1,
    ACTIONS(312), 1,
      sym_question,
    ACTIONS(314), 1,
      sym_number,
    STATE(131), 2,
      sym__expression,
      sym_identifier,
  [1764] = 1,
    ACTIONS(158), 5,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_comma_divider,
      anon_sym_LBRACE,
  [1772] = 1,
    ACTIONS(146), 5,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_comma_divider,
      anon_sym_LBRACE,
  [1780] = 4,
    ACTIONS(300), 1,
      aux_sym_identifier_token1,
    ACTIONS(316), 1,
      sym_question,
    ACTIONS(318), 1,
      sym_number,
    STATE(23), 2,
      sym__expression,
      sym_identifier,
  [1794] = 1,
    ACTIONS(152), 5,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_comma_divider,
      anon_sym_LBRACE,
  [1802] = 4,
    ACTIONS(300), 1,
      aux_sym_identifier_token1,
    ACTIONS(320), 1,
      sym_question,
    ACTIONS(322), 1,
      sym_number,
    STATE(132), 2,
      sym__expression,
      sym_identifier,
  [1816] = 4,
    ACTIONS(300), 1,
      aux_sym_identifier_token1,
    ACTIONS(324), 1,
      sym_question,
    ACTIONS(326), 1,
      sym_number,
    STATE(133), 2,
      sym__expression,
      sym_identifier,
  [1830] = 4,
    ACTIONS(300), 1,
      aux_sym_identifier_token1,
    ACTIONS(328), 1,
      sym_question,
    ACTIONS(330), 1,
      sym_number,
    STATE(20), 2,
      sym__expression,
      sym_identifier,
  [1844] = 1,
    ACTIONS(148), 5,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_comma_divider,
      anon_sym_LBRACE,
  [1852] = 4,
    ACTIONS(332), 1,
      aux_sym_identifier_token1,
    ACTIONS(334), 1,
      sym_question,
    ACTIONS(336), 1,
      sym_number,
    STATE(63), 2,
      sym__expression,
      sym_identifier,
  [1866] = 1,
    ACTIONS(202), 5,
      sym__newline,
      anon_sym_EQ,
      sym_lessThan_operator,
      sym_moreThan_operator,
      sym_in_operator,
  [1874] = 4,
    ACTIONS(300), 1,
      aux_sym_identifier_token1,
    ACTIONS(338), 1,
      sym_question,
    ACTIONS(340), 1,
      sym_number,
    STATE(129), 2,
      sym__expression,
      sym_identifier,
  [1888] = 4,
    ACTIONS(300), 1,
      aux_sym_identifier_token1,
    ACTIONS(342), 1,
      sym_question,
    ACTIONS(344), 1,
      sym_number,
    STATE(28), 2,
      sym__expression,
      sym_identifier,
  [1902] = 4,
    ACTIONS(300), 1,
      aux_sym_identifier_token1,
    ACTIONS(346), 1,
      sym_question,
    ACTIONS(348), 1,
      sym_number,
    STATE(21), 2,
      sym__expression,
      sym_identifier,
  [1916] = 4,
    ACTIONS(300), 1,
      aux_sym_identifier_token1,
    ACTIONS(350), 1,
      sym_question,
    ACTIONS(352), 1,
      sym_number,
    STATE(25), 2,
      sym__expression,
      sym_identifier,
  [1930] = 2,
    ACTIONS(356), 1,
      sym_comma_divider,
    ACTIONS(354), 4,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1940] = 2,
    ACTIONS(360), 1,
      sym_comma_divider,
    ACTIONS(358), 4,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
  [1950] = 4,
    ACTIONS(332), 1,
      aux_sym_identifier_token1,
    ACTIONS(362), 1,
      sym_question,
    ACTIONS(364), 1,
      sym_number,
    STATE(65), 2,
      sym__expression,
      sym_identifier,
  [1964] = 4,
    ACTIONS(300), 1,
      aux_sym_identifier_token1,
    ACTIONS(366), 1,
      sym_question,
    ACTIONS(368), 1,
      sym_number,
    STATE(24), 2,
      sym__expression,
      sym_identifier,
  [1978] = 1,
    ACTIONS(172), 4,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
  [1985] = 1,
    ACTIONS(116), 4,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1992] = 2,
    ACTIONS(372), 1,
      sym_number,
    ACTIONS(370), 2,
      aux_sym_identifier_token1,
      sym_question,
  [2000] = 3,
    ACTIONS(134), 1,
      sym__newline,
    STATE(5), 1,
      sym__block_start,
    STATE(59), 1,
      sym_block,
  [2010] = 3,
    ACTIONS(134), 1,
      sym__newline,
    STATE(5), 1,
      sym__block_start,
    STATE(58), 1,
      sym_block,
  [2020] = 3,
    ACTIONS(134), 1,
      sym__newline,
    STATE(5), 1,
      sym__block_start,
    STATE(57), 1,
      sym_block,
  [2030] = 3,
    ACTIONS(134), 1,
      sym__newline,
    STATE(2), 1,
      sym__block_start,
    STATE(52), 1,
      sym_block,
  [2040] = 3,
    ACTIONS(134), 1,
      sym__newline,
    STATE(2), 1,
      sym__block_start,
    STATE(54), 1,
      sym_block,
  [2050] = 3,
    ACTIONS(134), 1,
      sym__newline,
    STATE(2), 1,
      sym__block_start,
    STATE(61), 1,
      sym_block,
  [2060] = 1,
    ACTIONS(374), 1,
      anon_sym_DASH_GT,
  [2064] = 1,
    ACTIONS(376), 1,
      sym__indent,
  [2068] = 1,
    ACTIONS(378), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 42,
  [SMALL_STATE(4)] = 84,
  [SMALL_STATE(5)] = 126,
  [SMALL_STATE(6)] = 168,
  [SMALL_STATE(7)] = 207,
  [SMALL_STATE(8)] = 246,
  [SMALL_STATE(9)] = 285,
  [SMALL_STATE(10)] = 310,
  [SMALL_STATE(11)] = 335,
  [SMALL_STATE(12)] = 360,
  [SMALL_STATE(13)] = 385,
  [SMALL_STATE(14)] = 410,
  [SMALL_STATE(15)] = 435,
  [SMALL_STATE(16)] = 460,
  [SMALL_STATE(17)] = 485,
  [SMALL_STATE(18)] = 510,
  [SMALL_STATE(19)] = 532,
  [SMALL_STATE(20)] = 554,
  [SMALL_STATE(21)] = 576,
  [SMALL_STATE(22)] = 598,
  [SMALL_STATE(23)] = 620,
  [SMALL_STATE(24)] = 642,
  [SMALL_STATE(25)] = 664,
  [SMALL_STATE(26)] = 686,
  [SMALL_STATE(27)] = 698,
  [SMALL_STATE(28)] = 710,
  [SMALL_STATE(29)] = 732,
  [SMALL_STATE(30)] = 744,
  [SMALL_STATE(31)] = 766,
  [SMALL_STATE(32)] = 788,
  [SMALL_STATE(33)] = 800,
  [SMALL_STATE(34)] = 822,
  [SMALL_STATE(35)] = 834,
  [SMALL_STATE(36)] = 856,
  [SMALL_STATE(37)] = 878,
  [SMALL_STATE(38)] = 900,
  [SMALL_STATE(39)] = 912,
  [SMALL_STATE(40)] = 923,
  [SMALL_STATE(41)] = 934,
  [SMALL_STATE(42)] = 945,
  [SMALL_STATE(43)] = 956,
  [SMALL_STATE(44)] = 967,
  [SMALL_STATE(45)] = 978,
  [SMALL_STATE(46)] = 989,
  [SMALL_STATE(47)] = 1008,
  [SMALL_STATE(48)] = 1019,
  [SMALL_STATE(49)] = 1030,
  [SMALL_STATE(50)] = 1041,
  [SMALL_STATE(51)] = 1052,
  [SMALL_STATE(52)] = 1063,
  [SMALL_STATE(53)] = 1074,
  [SMALL_STATE(54)] = 1085,
  [SMALL_STATE(55)] = 1096,
  [SMALL_STATE(56)] = 1107,
  [SMALL_STATE(57)] = 1118,
  [SMALL_STATE(58)] = 1129,
  [SMALL_STATE(59)] = 1140,
  [SMALL_STATE(60)] = 1151,
  [SMALL_STATE(61)] = 1162,
  [SMALL_STATE(62)] = 1173,
  [SMALL_STATE(63)] = 1184,
  [SMALL_STATE(64)] = 1195,
  [SMALL_STATE(65)] = 1206,
  [SMALL_STATE(66)] = 1217,
  [SMALL_STATE(67)] = 1228,
  [SMALL_STATE(68)] = 1239,
  [SMALL_STATE(69)] = 1250,
  [SMALL_STATE(70)] = 1261,
  [SMALL_STATE(71)] = 1272,
  [SMALL_STATE(72)] = 1283,
  [SMALL_STATE(73)] = 1294,
  [SMALL_STATE(74)] = 1305,
  [SMALL_STATE(75)] = 1316,
  [SMALL_STATE(76)] = 1332,
  [SMALL_STATE(77)] = 1348,
  [SMALL_STATE(78)] = 1366,
  [SMALL_STATE(79)] = 1384,
  [SMALL_STATE(80)] = 1402,
  [SMALL_STATE(81)] = 1418,
  [SMALL_STATE(82)] = 1436,
  [SMALL_STATE(83)] = 1454,
  [SMALL_STATE(84)] = 1472,
  [SMALL_STATE(85)] = 1488,
  [SMALL_STATE(86)] = 1506,
  [SMALL_STATE(87)] = 1524,
  [SMALL_STATE(88)] = 1542,
  [SMALL_STATE(89)] = 1560,
  [SMALL_STATE(90)] = 1576,
  [SMALL_STATE(91)] = 1594,
  [SMALL_STATE(92)] = 1612,
  [SMALL_STATE(93)] = 1620,
  [SMALL_STATE(94)] = 1628,
  [SMALL_STATE(95)] = 1636,
  [SMALL_STATE(96)] = 1644,
  [SMALL_STATE(97)] = 1652,
  [SMALL_STATE(98)] = 1660,
  [SMALL_STATE(99)] = 1668,
  [SMALL_STATE(100)] = 1676,
  [SMALL_STATE(101)] = 1690,
  [SMALL_STATE(102)] = 1704,
  [SMALL_STATE(103)] = 1718,
  [SMALL_STATE(104)] = 1728,
  [SMALL_STATE(105)] = 1742,
  [SMALL_STATE(106)] = 1750,
  [SMALL_STATE(107)] = 1764,
  [SMALL_STATE(108)] = 1772,
  [SMALL_STATE(109)] = 1780,
  [SMALL_STATE(110)] = 1794,
  [SMALL_STATE(111)] = 1802,
  [SMALL_STATE(112)] = 1816,
  [SMALL_STATE(113)] = 1830,
  [SMALL_STATE(114)] = 1844,
  [SMALL_STATE(115)] = 1852,
  [SMALL_STATE(116)] = 1866,
  [SMALL_STATE(117)] = 1874,
  [SMALL_STATE(118)] = 1888,
  [SMALL_STATE(119)] = 1902,
  [SMALL_STATE(120)] = 1916,
  [SMALL_STATE(121)] = 1930,
  [SMALL_STATE(122)] = 1940,
  [SMALL_STATE(123)] = 1950,
  [SMALL_STATE(124)] = 1964,
  [SMALL_STATE(125)] = 1978,
  [SMALL_STATE(126)] = 1985,
  [SMALL_STATE(127)] = 1992,
  [SMALL_STATE(128)] = 2000,
  [SMALL_STATE(129)] = 2010,
  [SMALL_STATE(130)] = 2020,
  [SMALL_STATE(131)] = 2030,
  [SMALL_STATE(132)] = 2040,
  [SMALL_STATE(133)] = 2050,
  [SMALL_STATE(134)] = 2060,
  [SMALL_STATE(135)] = 2064,
  [SMALL_STATE(136)] = 2068,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(100),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(109),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(119),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(113),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(101),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(88),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(64),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(115),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(118),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(120),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(124),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(123),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(82),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(53),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dictionary_type_repeat1, 2), SHIFT_REPEAT(90),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dictionary_type_repeat1, 2), SHIFT_REPEAT(30),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dictionary_type_repeat1, 2), SHIFT_REPEAT(12),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dictionary_type_repeat1, 2),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_type, 3),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_type, 2),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_type, 2),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_type, 3),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dictionary_type, 2),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [166] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_type_repeat1, 2), SHIFT_REPEAT(83),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_type_repeat1, 2), SHIFT_REPEAT(19),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_type_repeat1, 2),
  [174] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_type_repeat1, 2), SHIFT_REPEAT(17),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dictionary_type, 3),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__block_start, 2),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_function_definition, 3, .production_id = 3),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_definition, 3),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_variable_definition_repeat1, 2),
  [191] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_variable_definition_repeat1, 2), SHIFT_REPEAT(103),
  [194] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_variable_definition_repeat1, 2), SHIFT_REPEAT(46),
  [197] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_variable_definition_repeat1, 2), SHIFT_REPEAT(46),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier, 1),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_function_definition, 3, .production_id = 1),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_function_definition, 5, .production_id = 6),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_plain_text, 1),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while_function_definition, 5, .production_id = 5),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_definition, 4),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_function_definition, 5, .production_id = 4),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_save_command_definition, 2),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_question_function_definition, 2),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_while_function_definition, 3, .production_id = 2),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [232] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [240] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [254] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [260] = {.entry = {.count = 1, .reusable = false}}, SHIFT(78),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [268] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [276] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [282] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dictionary_pair, 3),
  [290] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [292] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [296] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [300] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [302] = {.entry = {.count = 1, .reusable = false}}, SHIFT(130),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [306] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_identifier, 1),
  [308] = {.entry = {.count = 1, .reusable = false}}, SHIFT(128),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [312] = {.entry = {.count = 1, .reusable = false}}, SHIFT(131),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [316] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [320] = {.entry = {.count = 1, .reusable = false}}, SHIFT(132),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [324] = {.entry = {.count = 1, .reusable = false}}, SHIFT(133),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [328] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [332] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [334] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [338] = {.entry = {.count = 1, .reusable = false}}, SHIFT(129),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [342] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [346] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [350] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [354] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dictionary_type_repeat1, 1),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [358] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_type_repeat1, 1),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [362] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [366] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [370] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_equal_operator, 1),
  [372] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_equal_operator, 1),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [378] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_GuidedTrack_external_scanner_create(void);
void tree_sitter_GuidedTrack_external_scanner_destroy(void *);
bool tree_sitter_GuidedTrack_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_GuidedTrack_external_scanner_serialize(void *, char *);
void tree_sitter_GuidedTrack_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_GuidedTrack(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_GuidedTrack_external_scanner_create,
      tree_sitter_GuidedTrack_external_scanner_destroy,
      tree_sitter_GuidedTrack_external_scanner_scan,
      tree_sitter_GuidedTrack_external_scanner_serialize,
      tree_sitter_GuidedTrack_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
